### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by Alroha** [Spoorloos/uwp_executor#1]
The object or library file 'C:\Users\Alroha\\Desktop\uwp_executor-main\Dependencies\zstd\lib\libzstd_static.lib' was created by a different version of the compiler than other objects like 'Release\Execution.obj'; rebuild all objects and libraries with the same compiler

LNK1257	code generation failed

**Comment by Alroha** [comment]
errors*

**Comment by Spoorloos** [comment]
You're most likely not using the 2022 version of Visual Studio and changed the platform toolset when you opened up the project.

**Comment by Alroha** [comment]
I am using VS 2022

**Comment by Alroha** [comment]
Should i set it to Release x86?

**Comment by Alroha** [comment]
It compiled now but roblox crashed

**Comment by Spoorloos** [comment]
> Should i set it to Release x86?

It should be on Release x86 by default, I removed the other options.

> It compiled now but roblox crashed

It's not updated, you'll have to update the offsets yourself.

**Comment by Alroha** [comment]
How do i find the offsets? I have open an dumped roblox in IDA freeware but i don't know how to find all the offsets. If you could give me an quick guide id appreciate it

**Comment by Spoorloos** [comment]
> How do i find the offsets? I have open an dumped roblox in IDA freeware but i don't know how to find all the offsets. If you could give me an quick guide id appreciate it

Add me on discord (check profile)

**Comment by altacountbabi** [comment]
same issue here, im using vs 2022

**Comment by t0int1337** [comment]
I had to change o x86 too the default was x64
