### ISSUE TITLE
Scheduler Hook, Teleport Handling 

### ISSUE THREAD

**Issue by ImmuneLion318** [Spoorloos/uwp_executor#12]
I Think It'd Nice If You Added These For Hopefully People To Learn They Are Both Easy To Achieve And Should Be Fairly Simple Todo.

**Comment by Spoorloos** [comment]
> I Think It'd Nice If You Added These For Hopefully People To Learn They Are Both Easy To Achieve And Should Be Fairly Simple Todo.

Nuh Uh

**Comment by ImmuneLion318** [comment]
Why Not Both Are Achieved Relatively Easy.

**Comment by Spoorloos** [comment]
> Why Not Both Are Achieved Relatively Easy.

Scheduler Hooks Look Mad Ugly.
