### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by altacountbabi** [Spoorloos/uwp_executor#3]
for some reason I keep getting this error when trying to compile:
```
The object or library file 'libzstd_static.lib' was created by a different version of the compiler than other objects like 'Release\dllmain.obj'; rebuild all objects and libraries with the same compiler.
```
Im using vs 2022, please help me

**Comment by Spoorloos** [comment]
Update your Visual Studio to the latest version.

**Comment by altacountbabi** [comment]
@Spoorloos ok so, it compiled now and I managed to print hello world but when i actually tried to use the execute_script function roblox just froze and crashed

**Comment by cinarkagan** [comment]
same

**Comment by cinarkagan** [comment]
as far as i noticed
it is an issue of raise identity

**Comment by altacountbabi** [comment]
> as far as i noticed it is an issue of raise identity

It doesnt seem to work even if i dont raise the identity

**Comment by Spoorloos** [comment]
> > as far as i noticed it is an issue of raise identity
> 
> It doesnt seem to work even if i dont raise the identity

what are you executing

**Comment by altacountbabi** [comment]
@Spoorloos im not trying to run anything special, just `printidentity()`

**Comment by Spoorloos** [comment]
> @Spoorloos im not trying to run anything special, just `printidentity()`

The source is already functional right now? Just download the it, compile it and inject with a manual map dll injector.

**Comment by altacountbabi** [comment]
@Spoorloos I've downloaded the latest version and it compiled but roblox still just crashes, and yes im on the right roblox version.

**Comment by Spoorloos** [comment]
> @Spoorloos I've downloaded the latest version and it compiled but roblox still just crashes, and yes im on the right roblox version.

Try again now.

**Comment by altacountbabi** [comment]
@Spoorloos didnt seem to fix it, I pulled from the git repo and recompiled, am I missing something?

**Comment by Spoorloos** [comment]
> @Spoorloos didnt seem to fix it, I pulled from the git repo and recompiled, am I missing something?

Add me on discord.
