### ISSUE TITLE
I understand that this is off topic

### ISSUE THREAD

**Issue by maximus04132** [Spoorloos/uwp_executor#4]
how do I add it to my program? that is, can you tell me functions such as execute, inject for monaco? and also, how do I update it in the future? my discord maximus04133#1207

**Comment by SimplyTiramisu** [comment]
I admire your desire to learn, but this source isn't for that. This source doesn't support namedpipes (which is common to communicate between your UI and DLL for scripts). It only executes printidentity() or whatever you put in Main.cpp. You'll need to implement a communication method yourself (A good way to practice your C++ skills!)
