### ISSUE TITLE
Cannot use any CoreGUI related scripts.

### ISSUE THREAD

**Issue by t0int1337** [Spoorloos/uwp_executor#5]
![image](https://github.com/Spoorloos/uwp_executor/assets/138823941/c014c376-2b34-4ee1-9cc3-51d81706daf3)

I cannot execute scripts that have interfaces. Could this be fixed? Or how I would like to contribute to the project.

**Comment by t0int1337** [comment]
IDK much about lua but I also cannot use LocalPlayer.Character.

**Comment by Spoorloos** [comment]
> I cannot execute scripts that have interfaces. Could this be fixed? Or how I would like to contribute to the project.

It's supposed to be like this, for now at least. We have a fix but aren't ready to make it public yet. Also know that the executor isn't meant for actual use, it's just a source to learn from.
