### ISSUE TITLE
Lua not working properly

### ISSUE THREAD

**Issue by serbinskis** [Spoorloos/uwp_executor#8]
When running lau script it runs, but it has no access to many things. For example, if I run `warn(game.PlaceId)` it will just prints 0. I already updated offsets in Roblox.hpp.

**Comment by WobbyChip** [comment]
I think the issue is that we are getting a global state, instead of the current one. How do you get state from when you join the game?

**Comment by Spoorloos** [comment]
> it can only do real basic stuff like print i hope it gets updated to work for all lua code

It won't, this project is only meant as a resource for others to learn basic script execution with. Custom functions, an identity bypass and everything else will be up to them.

**Comment by iocmet** [comment]
Hi can you explain why it can do only basics?
