### ISSUE TITLE
inject failiure

### ISSUE THREAD

**Issue by PikachuGabe** [Spoorloos/uwp_executor#9]
attempting to inject .dll into microsoft store version of roblox, but i get a "attempting to inject 32 bit dll into 64 bit process" error

**Comment by Spoorloos** [comment]
Make sure you're injecting into the right process "Windows10Universal.exe"

**Comment by PikachuGabe** [comment]
i managed to inject it, but roblox crashes on inject with event viewer logging info that i will attach as a .txt
[a.txt](https://github.com/Spoorloos/uwp_executor/files/12499799/a.txt)

**Comment by Spoorloos** [comment]
> i managed to inject it, but roblox crashes on inject with event viewer logging info that i will attach as a .txt [a.txt](https://github.com/Spoorloos/uwp_executor/files/12499799/a.txt)

Try now, the scheduler offsets were outdated.

**Comment by PikachuGabe** [comment]
now i get this crash, after injecting. 
[error.txt](https://github.com/Spoorloos/uwp_executor/files/12504502/error.txt)
[windows error report.txt](https://github.com/Spoorloos/uwp_executor/files/12504503/windows.error.report.txt)
using extreme injector in secure mode with extreme scrambling, manual injection, erase PE, hide module and stealth inject

**Comment by Spoorloos** [comment]
> now i get this crash, after injecting. [error.txt](https://github.com/Spoorloos/uwp_executor/files/12504502/error.txt) [windows error report.txt](https://github.com/Spoorloos/uwp_executor/files/12504503/windows.error.report.txt) using extreme injector in secure mode with extreme scrambling, manual injection, erase PE, hide module and stealth inject

Use these settings and make sure your roblox is updated.
![image](https://github.com/Spoorloos/uwp_executor/assets/59575072/feb72cb3-4849-42f0-a3ed-43433ac5356b)

**Comment by PikachuGabe** [comment]
now it injects, but how do i run scripts with it?
